# -*- coding: utf-8 -*-
"""
Django settings for website4 project DEVELOP.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

# ==============================================================================
#  Copyright (C) 2023 Sakuyark, Inc. All Rights Reserved                       =
#                                                                              =
#    @Time : 2023-6-20 17:13                                                   =
#    @Author : hanjin                                                          =
#    @Email : 2819469337@qq.com                                                =
#    @File : prod.py                                                           =
#    @Program: website5                                                        =
# ==============================================================================

import os
import sys
from pathlib import Path

DJANGO_APPS_PATH = str(Path(os.environ['DJANGO_APPS_PATH']).absolute())
sys.path.append(DJANGO_APPS_PATH)

from global_settings.prod import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("WEBSITE_SECRET_KEY")

# Application definition
INSTALLED_APPS += [
    "Blossom"
]

# 忽略部分问题
SILENCED_SYSTEM_CHECKS += []

MIDDLEWARE += []

ROOT_URLCONF = 'backend.urls'

WSGI_APPLICATION = 'backend.wsgi.application'

AUTHENTICATION_BACKENDS = (
    'account.auth.UserBackend',
)

AUTH_USER_MODEL = 'account.User'

AUTH_PASSWORD_VALIDATORS += []

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "appfront/dist/static"),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['appfront/dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DJOSER = {
    'SITE_NAME': 'Sakuyark',
    'SEND_ACTIVATION_EMAIL': True,
    'ACTIVATION_URL': 'activation/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_URL': 'reset_password/{uid}/{token}',
    "serializers": {
        "current_user": "account.serializers.UserSerializer",
    },
    "permissions":
        {
            "activation": ["rest_framework.permissions.AllowAny"],
            "password_reset": ["rest_framework.permissions.AllowAny"],
            "password_reset_confirm": ["rest_framework.permissions.AllowAny"],
            "set_password": ["account.permissions.CurrentUserOrAdmin"],
            "username_reset": ["rest_framework.permissions.AllowAny"],
            "username_reset_confirm": ["rest_framework.permissions.AllowAny"],
            "set_username": ["account.permissions.CurrentUserOrAdmin"],
            "set_avatar": ["account.permissions.CurrentUserOrAdmin"],
            "set_signature": ["account.permissions.CurrentUserOrAdmin"],
            "user_create": ["rest_framework.permissions.AllowAny"],
            "user_delete": ["account.permissions.CurrentUserOrAdmin"],
            "user": ["account.permissions.CurrentUserOrAdmin"],
            "user_list": ["account.permissions.CurrentUserOrAdmin"],
            "token_create": ["rest_framework.permissions.AllowAny"],
            "token_destroy": ["rest_framework.permissions.IsAuthenticated"],
        }

}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "Sakuyark@163.com"
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_FROM = "Sakuyark"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
HOST_URL = "http://127.0.0.1"

PHONENUMBER_DEFAULT_REGION = "CN"
PHONENUMBER_DB_FORMAT = "INTERNATIONAL"
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"

BASE_URL = ""

CRONJOBS = []

# 个推信息设置
GETUI_BASE_URL = 'https://restapi.getui.com/v2/'
APP_ID = '******'
APP_KEY = '******'
APP_SECRET = '******'
MASTER_SECRET = '******'
